### ISSUE TITLE
Plans for Dawntrail update?

### ISSUE THREAD

**Issue by Kosba2** [redstrate/Rebound#2]
Hi, apologies for making this kind of post, but I was wondering if there were plans for a Dawntrail release? I loved this mod, as I didn't know this game even had those sorta physics, and this is the one that fixed them for me. Unfortunately it's currently it's marked outdated on Dalamud so I can't enable it.

**Comment by redstrate** [comment]
I updated it for Dawntrail recently, weird that Dalamud is now marking it out of date. Something probably changed, I'll look into it soon and hopefully this weekend.

**Comment by redstrate** [comment]
Hmm, I tried uninstalling it and my Dalamud isn't marking it as outdated:

![image](https://github.com/user-attachments/assets/9f010590-610a-4cd1-a9de-2c3b51af3a8f)

(I'm running staging though, I'm not sure if that has any effect.)

Are you sure you're getting it from the repository and you don't have a local DLL build sitting around?

**Comment by Kosba2** [comment]
![image](https://github.com/user-attachments/assets/c0030887-3a63-428f-9f47-111a5242c087)

So before I delete and reinstall it, here's a picture to prove my own sanity.... and yeup reinstalling it fixed the flag for me!

![image](https://github.com/user-attachments/assets/8f6276cb-48b2-467e-bf16-6d0e05f9dff2)

My apologies, this must have been a Dalamud issue, as I had problems with things not leaving the Experimental Branch recently too. Sorry to worry you, and thank you for the wonderful mod.
